version: 2

builds:
  - main: ./cmd/webhook
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath # removes all file system paths from the compiled executable
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ .ProjectName }}_v{{ .Version }}"

changelog:
  sort: asc

dockers:
  - image_templates:
      - "ghcr.io/pixelunioneu/external-dns-bunny-webhook:{{ .Tag }}-amd64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/pixelunioneu/external-dns-bunny-webhook:{{ .Tag }}-arm64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/pixelunioneu/external-dns-bunny-webhook:latest"
    image_templates:
      - "ghcr.io/pixelunioneu/external-dns-bunny-webhook:{{ .Tag }}-amd64"
      - "ghcr.io/pixelunioneu/external-dns-bunny-webhook:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/pixelunioneu/external-dns-bunny-webhook:{{ .Tag }}"
    image_templates:
      - "ghcr.io/pixelunioneu/external-dns-bunny-webhook:{{ .Tag }}-amd64"
      - "ghcr.io/pixelunioneu/external-dns-bunny-webhook:{{ .Tag }}-arm64"
release:
  github:
    owner: contaimlabs
    name: external-dns-bunny-webhook
